spring.application.name=Presteo
environment=${ENV:dev}
hostname=${HOSTNAME:localhost}
fronturl=${HOSTNAME:localhost:3000}

# Configuration Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=10

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuration du serveur
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

# Configuration du logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuration Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.enable-spring-security=false
server.servlet.session.cookie.same-site=none

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Resend
resend.api-key=${RESEND_API_KEY}

# Google Cloud Storage Configuration
gcp.project-id=presteo
gcp.credentials.location=classpath:presteo-service-account.json
gcs.bucket.name=images-presteo
gcs.folder.user-profile-images=user-profile-images
gcs.folder.service-images=service-images
